language: objective-c
osx_image: xcode9.4
xcode_workspace: Alamofire.xcworkspace
matrix:
  include:
    - xcode_scheme: Alamofire iOS
      xcode_destination: OS=11.4,name=iPhone X
    - xcode_scheme: Alamofire tvOS
      xcode_destination: OS=11.4,name=Apple TV 4K
    - xcode_scheme: Alamofire macOS
      xcode_destination: arch=x86_64
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - gem update --system 2.7.6 # needed for pod lint to work (https://github.com/CocoaPods/CocoaPods/issues/7765)
  - gem install xcpretty cocoapods # normally we install these, but if the project chooses an alternate ruby, they need to install them
notifications:
  email: false
